apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata: 
  name: xaks.azure.platform.io
spec:
  group: azure.platform.io
  names:
    kind: xAks
    plural: xaks
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              instance_type:
                type: string
              count:
                type: integer
                description: Desired node count, from 1 to 100.
                default: 2
              location:
                type: string
              vnet_cidr:
                type: string
              subnet_cidr:
                type: string
  claimNames:
    kind: Environment
    plural: environments
